name: Auto Deploy

on:
  push:
    branches: [ main ] # 只要推送到 main 分支就触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 拿代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 装环境
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. 打包 (生成 dist 文件夹)
      - name: Build
        run: |
          npm install
          npm run build

      # 4. 传文件到服务器
      - name: Upload to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          target: "/opt/1panel/apps/openresty/openresty/www/sites/home.npu127.com/index"
          source: "dist/*"
          strip_components: 1